diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Users/netadmin/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.password=morkazak2323.
user.mail=tunc.aksuna$ git config --global user.mail tunc.aksuna
user.name=tuncAksuna
user.email=aksuna.tunc@gmail.com
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
user.email=aksuna.tunc@gmail.com
user.name=tuncAksuna
remote.upstream.url=https://github.com/tuncAksuna/full-stack-angular-sboot.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
remote.origin.url=https://github.com/tuncAksuna01/full-stack-angular-sboot.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
