version: "3.4"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: employee_management_system
      MYSQL_USER: root
      MYSQL_RANDOM_PASSWORD: "1"
      MYSQL_PASSWORD: M.orkazak2323.

